### ISSUE TITLE
[Phase 2] Build category page UI

### ISSUE THREAD

**Issue by zhzhang2012** [Haunter17/CS121-RecyclingApp#15]
- [x] Build a basic category page UI following the same theme we use
  - [x] Build routes for category page, presumably `GET /categories/:id`
  - [x] Link the pages to corresponding links on the main page
  - [x] Modify Navbar for category page
  - [x] Adding footer html
  - [x] Modify category table margin

**Comment by Haunter17** [comment]
Done

**Comment by zhzhang2012** [comment]
Cool
