### ISSUE TITLE
[Phase 4] Edit city page to show full information including contacts and additional files

### ISSUE THREAD

**Issue by hmc-cs-dwang** [Haunter17/CS121-RecyclingApp#43]
- [x] Additional files need routing for pdf files download
- [x] Add contacts section for city

**Comment by zhzhang2012** [comment]
@hmc-cs-dwang  Just did this

**Comment by hmc-cs-dwang** [comment]
@zhzhang2012 Routing for pdf done?

**Comment by zhzhang2012** [comment]
@hmc-cs-dwang Oh not really. Did the second item

**Comment by zhzhang2012** [comment]
Close after Commit #207
