### ISSUE TITLE
Fix two rails & Docker bug in dev environment

### ISSUE THREAD

**Issue by zhzhang2012** [Haunter17/CS121-RecyclingApp#5]
Fix two existing bugs that relate to running Dockerized rails framework:

  - Automatic exit after creating the container. This is due to incorrect volume sync of `tmp` folder
  - Network IP error. The solution of this error could be found here: http://stackoverflow.com/questions/29417328/how-to-disable-cannot-render-console-from-on-rails

**Comment by Haunter17** [comment]
* 老哥**稳**
* 螺旋**稳**
